### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by olga-dibrova** [olga-dibrova/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by sweet-lost** [comment]
<h2> Résumé</h2>

— Hello! I am seeking for a position of Junior QA because I am interested in ways to make the product better. I have the goals and I will do whatever it takes to achieve them. Nothing is impossible when I have a time! =)

**Comment by olga-dibrova** [comment]
Thanks!
