### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by olga-dibrova** [olga-dibrova/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by sweet-lost** [comment]
tel. +380665567153
Email olga.dibrova.v@gmail.com
https://www.instagram.com/sweet.lost/
https://www.facebook.com/olga.dibrova/

**Comment by olga-dibrova** [comment]
Good!)
