### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by olga-dibrova** [olga-dibrova/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by sweet-lost** [comment]
EXPERIENCE
2019 - practice at JoinPro.ru project
prepared CheckLists and Bug reports at project

2016-2020 - worked as assistant and administrator at father's stomatology clinic
prepared documentation and workspace

2013-2019 - assistant at the Economic Cybernetic and Marketing Department
conducted lectures and practical classes "E-commerce", "Information security" for students of Economics & Business Faculty

EDUCATION
2019 - QA course at ITStart
2014-2015 Java Development at InfopulseUniver
2009-2010 Interior Design at School of architectural design of educational center "Успіх" 
2008-2018 Economic Cybernetic at Kyiv National University of Technologies and Design
         2008-2013 Bachelor, Master degree
         2013-2016 Postgraduate
