### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by olga-dibrova** [olga-dibrova/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by sweet-lost** [comment]
Languages:
Czech, English, Russian, Ukrainian

Skills:
Software Development Lifecycle, SDLC methodologies (Waterfall, V-model, spiral),Types of testing, Levels of testing, Test Artifacts, Test Plan, Test Case, Test Report, RTM, Check-lists, Bug report, Bug lifecycle, Test design techniques, Agile, Scrum basics
Client-server app understanding,HTTP/HTTPS protocol (request/responsee structure), Chome DEV Tools, Basics SQL, Basic HTML, CSS understanding, Basic OOP

Character:
open-minded, honest, loyal, adaptive, watchful, hard-working, considerate, responsible, creative, friendly, cooperative diligent, flexible, quality-minded, have an eye for detail


Hobby: 
ballet, modern dance, languages, photography, painting, hand-made, hiking, reeding, classical music
